#!/bin/bash

echo "==================================="
echo "Creating GitHub Repository"
echo "==================================="
echo ""
echo "Option 1: Open browser to create repository manually"
echo "------------------------------------------------------"
echo "Visit: https://github.com/new"
echo ""
echo "Settings:"
echo "  - Repository name: movie-utopia-v2"
echo "  - Description: AI Film Creation Platform - Movie Utopia v2"
echo "  - Visibility: Public (or Private)"
echo "  - DO NOT initialize with README, .gitignore, or license"
echo ""
echo "After creating the repository, run:"
echo "  git push -u origin main"
echo ""
echo "==================================="
